site_name: Math Problems

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: pl
          name: Polski
          default: true
          build: true
          nav:
            - Home: 'index.md'
            - Algebra:
              - '1. Macierze i operacje': '1_Algebra/01_matrices_and_operations.md'
              - '2. Wyznaczniki': '1_Algebra/02_determinants.md'
              - '3. Odwracanie macierzy': '1_Algebra/03_matrix_inversion.md'
              - '4. Układy równań': '1_Algebra/04_systems_of_equations.md'
            - Geometria:
              - '1. Wektory': '2_Geometria/01_vectors.md'
              - '2. Proste': '2_Geometria/02_lines.md'
              - '3. Płaszczyzny': '2_Geometria/03_planes.md'
              - '4. Prosta i płaszczyzna': '2_Geometria/04_line_and_plane.md'
            - Analiza:
              - '1. Granice ciągów': '3_Analiza/01_sequence_limits.md'
              - '2. Granice funkcji': '3_Analiza/02_function_limits.md'
              - '3. Pochodne funkcji': '3_Analiza/03_derivatives.md'
              - '4. Badanie funkcji': '3_Analiza/04_function_analysis.md'
              - '5. Całki': '3_Analiza/05_integrals.md'
            - Metody probabilistyczne:
              - '1. Zdarzenia i prawdopodobieństwo': '4_Metody_probabilistyczne/01_events_and_probability.md'
              - '2. Zmienne losowe': '4_Metody_probabilistyczne/02_random_variables.md'
              - '3. Parametry rozkładu': '4_Metody_probabilistyczne/03_distribution_parameters.md'
              - '4. Wybrane rozkłady': '4_Metody_probabilistyczne/04_selected_distributions.md'
              - '5. Twierdzenia graniczne': '4_Metody_probabilistyczne/05_limit_theorems.md'
              - '6. Podstawowe statystyki': '4_Metody_probabilistyczne/06_basic_statistics.md'
              - '7. Estymacja': '4_Metody_probabilistyczne/07_estimation.md'
              - '8. Weryfikacja hipotez': '4_Metody_probabilistyczne/08_hypothesis_testing.md'
              - '9. Korelacja i regresja': '4_Metody_probabilistyczne/09_correlation_and_regression.md'
              - '10. Zaawansowane metody': '4_Metody_probabilistyczne/10_advanced_methods.md'
              - '11. Teoria decyzji': '4_Metody_probabilistyczne/11_decision_theory.md'
        - locale: en
          name: English
          build: true
          nav:
            - Home: 'index.md'