site_name: Math Problems
site_url: https://dchorazkiewicz.github.io/Math_Problems_Repo/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: pl
          name: Polski
          build: true
          nav:
            - Home: 'index.md'
            - Algebra:
              - '1. Macierze i operacje': '1_Algebra/01_matrices_and_operations.md'
              - '2. Wyznaczniki': '1_Algebra/02_determinants.md'
              - '3. Odwracanie macierzy': '1_Algebra/03_matrix_inversion.md'
              - '4. Układy równań': '1_Algebra/04_systems_of_equations.md'
            - Geometria:
              - '1. Wektory': '2_Geometria/01_vectors.md'
              - '2. Proste': '2_Geometria/02_lines.md'
              - '3. Płaszczyzny': '2_Geometria/03_planes.md'
              - '4. Prosta i płaszczyzna': '2_Geometria/04_line_and_plane.md'
            - Analiza:
              - '1. Granice ciągów': '3_Analiza/01_sequence_limits.md'
              - '2. Granice funkcji': '3_Analiza/02_function_limits.md'
              - '3. Pochodne funkcji': '3_Analiza/03_derivatives.md'
              - '4. Badanie funkcji': '3_Analiza/04_function_analysis.md'
              - '5. Całki': '3_Analiza/05_integrals.md'
            - Metody probabilistyczne:
              - '1. Zdarzenia i prawdopodobieństwo': '4_Metody_probabilistyczne/01_events_and_probability.md'
              - '2. Zmienne losowe': '4_Metody_probabilistyczne/02_random_variables.md'
              - '3. Parametry rozkładu': '4_Metody_probabilistyczne/03_distribution_parameters.md'
              - '4. Wybrane rozkłady': '4_Metody_probabilistyczne/04_selected_distributions.md'
              - '5. Twierdzenia graniczne': '4_Metody_probabilistyczne/05_limit_theorems.md'
              - '6. Podstawowe statystyki': '4_Metody_probabilistyczne/06_basic_statistics.md'
              - '7. Estymacja': '4_Metody_probabilistyczne/07_estimation.md'
              - '8. Weryfikacja hipotez': '4_Metody_probabilistyczne/08_hypothesis_testing.md'
              - '9. Korelacja i regresja': '4_Metody_probabilistyczne/09_correlation_and_regression.md'
              - '10. Zaawansowane metody': '4_Metody_probabilistyczne/10_advanced_methods.md'
              - '11. Teoria decyzji': '4_Metody_probabilistyczne/11_decision_theory.md'
            - Animacje:
              - Metody probabilistyczne:
                - 'Lista 1': 'anim/4_Metody_probalistyczne/prob_list_1.html'
                - 'Lista 2': 'anim/4_Metody_probalistyczne/prob_list_2.html'
                - 'Lista 3': 'anim/4_Metody_probalistyczne/prob_list_3.html'
        - locale: en
          name: English
          default: true
          build: true
          nav:
            - Home: 'index.md'
            - Algebra:
              - '1. Matrices & Operations': '1_Algebra/01_matrices_and_operations.md'
              - '2. Determinants': '1_Algebra/02_determinants.md'
              - '3. Matrix Inversion': '1_Algebra/03_matrix_inversion.md'
              - '4. Systems of Equations': '1_Algebra/04_systems_of_equations.md'
            - Geometry:
              - '1. Vectors': '2_Geometria/01_vectors.md'
              - '2. Lines': '2_Geometria/02_lines.md'
              - '3. Planes': '2_Geometria/03_planes.md'
              - '4. Line and Plane': '2_Geometria/04_line_and_plane.md'
            - Analysis:
              - '1. Sequence Limits': '3_Analiza/01_sequence_limits.md'
              - '2. Function Limits': '3_Analiza/02_function_limits.md'
              - '3. Derivatives': '3_Analiza/03_derivatives.md'
              - '4. Function Analysis': '3_Analiza/04_function_analysis.md'
              - '5. Integrals': '3_Analiza/05_integrals.md'
            - Probabilistic Methods:
              - '1. Events & Probability': '4_Metody_probabilistyczne/01_events_and_probability.md'
              - '2. Random Variables': '4_Metody_probabilistyczne/02_random_variables.md'
              - '3. Distribution Parameters': '4_Metody_probabilistyczne/03_distribution_parameters.md'
              - '4. Selected Distributions': '4_Metody_probabilistyczne/04_selected_distributions.md'
              - '5. Limit Theorems': '4_Metody_probabilistyczne/05_limit_theorems.md'
              - '6. Basic Statistics': '4_Metody_probabilistyczne/06_basic_statistics.md'
              - '7. Estimation': '4_Metody_probabilistyczne/07_estimation.md'
              - '8. Hypothesis Testing': '4_Metody_probabilistyczne/08_hypothesis_testing.md'
              - '9. Correlation & Regression': '4_Metody_probabilistyczne/09_correlation_and_regression.md'
              - '10. Advanced Methods': '4_Metody_probabilistyczne/10_advanced_methods.md'
              - '11. Decision Theory': '4_Metody_probabilistyczne/11_decision_theory.md'
            - Animations:
              - Probabilistic Methods:
                - 'List 1': 'anim/4_Metody_probalistyczne/prob_list_1.html'
                - 'List 2': 'anim/4_Metody_probalistyczne/prob_list_2.html'
                - 'List 3': 'anim/4_Metody_probalistyczne/prob_list_3.html'